### PR TITLE
added Ruth as an attendee

### PR DESCRIPTION
**Pull request by nanjalaruth**

### CODE REVIEW

**Comment by Nikoleta-v3** [comment]
Thank you @nanjalaruth for your pull request! 😄 It looks great. Could you please edit the line `Name - Ruth Nanjala` to be `- name: Ruth Nanjala`? and similar `GitHub - nanjalaruth` to be `github: nanjalaruth`!

**Comment by nanjalaruth** [comment]
Working on it. Thanks

**Comment by nanjalaruth** [comment]
I have made the edits @Nikoleta-v3

**Comment by Nikoleta-v3** [comment]
Looks great! Thank you @nanjalaruth 🎉

**Pull request merged**
