### PR TITLE
Create Bonface.yml

### PR DESCRIPTION
**Pull request by bonfaceonyango**
Added Bonface as an attendee

### CODE REVIEW

**Comment by Nikoleta-v3** [comment]
Thank you again @Boniformatics!  In the `Files changed` tab you can click on the three dots on the right `...`.  There you can click on `Edit`! Could you please add the symbol `-` before `name`? 😄 🎉

**Comment by bonfaceonyango** [comment]
Thanks for the correction. You can check if it's okay

**Comment by Nikoleta-v3** [comment]
Great! Well done on making the change 😃 

Now it should be `- name:` instead on `name` and could you add two spaces before `github`?

**Comment by Nikoleta-v3** [comment]
Thank you @Boniformatics 🎉

**Comment by bonfaceonyango** [comment]
Awesome, thanks too!

**Pull request merged**
